# Generated by Django 3.2.6 on 2021-10-10 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_system', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecommendationModel',
        ),
    ]
