# Generated by Django 3.2.6 on 2021-10-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommender_system', '0002_delete_recommendationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationSystemModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('college_code', models.IntegerField()),
                ('college_name', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('college_location', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('seat_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('minority', models.CharField(max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'recommendation_system_2021',
            },
        ),
    ]
