# Generated by Django 3.2.6 on 2021-10-30 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_system', '0003_recommendationsystemmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recommendationsystemmodel',
            table='recommendation_system_21',
        ),
    ]
